// Copyright Narrative Tools 2024. 

#pragma once

#include "CoreMinimal.h"
#include "Logging/LogMacros.h"

class UObject;

NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogSettlements, Log, All);
NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogSaveSystem, Log, All);
NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogNPCs, Log, All);
NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogNavigator, Log, All);

NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogNarrativeAbilities, Log, All);
NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogNarrativeCombat, Log, All);

NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogNarrativeItem, Log, All);
NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogNarrativeInventory, Log, All);
NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogNarrativeCharacter, Log, All);
NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogNarrativeCharacterVisual, Log, All);

NARRATIVEPRO_API DECLARE_LOG_CATEGORY_EXTERN(LogNarrativeActivityComponent, Log, All);